CREATE TABLE Bureau (
    SK_ID_BUREAU INT PRIMARY KEY,
    SK_ID_CURR INT,
    DAYS_CREDIT INT,
    AMT_CREDIT_SUM FLOAT,
    CREDIT_SUM_LIMIT FLOAT,
    CREDIT_TYPE VARCHAR(50)
);

CREATE TABLE Bureau_Balance (
    SK_ID_BUREAU INT,
    MONTHS_BALANCE INT,
    STATUS VARCHAR(10)
);

CREATE TABLE POS_CASH_Balance (
    SK_ID_CURR INT,
    SK_ID_PREV INT,
    CNT_INSTALMENT INT,
    MONTHS_BALANCE INT
);

CREATE TABLE Previous_Application (
    SK_ID_PREV INT PRIMARY KEY,
    NAME_PAYMENT_TYPE VARCHAR(50),
    CNT_PAYMENT INT,
    DAYS_LAST_DUE INT,
    DAYS_TERMINATION INT,
    SELLERPLACE_AREA INT,
    NAME_PORTFOLIO VARCHAR(50)
);

CREATE TABLE Installment_Payments (
    SK_ID_CURR INT,
    SK_ID_PREV INT,
    DAYS_INSTALLMENT INT,
    AMT_INSTALLMENT FLOAT
);

CREATE TABLE Credit_Card_Balance (
    SK_ID_PREV INT,
    AMT_DRAWINGS_CURRENT FLOAT,
    AMT_PAYMENT_CURRENT FLOAT
);
